version: '3.3'

services:
 reverse-proxy:
   image: nginx:1.17.10
   container_name: reverse_proxy_demo
   depends_on:
       - repartidor
       - restaurante
       - esb
   volumes:
     - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
   ports:
     - 80:80
 repartidor:
  image: repartido
  build:
   context: ./src/Repartidor
  ports:
   - "8080:8080"
  networks:
   - docker_xxx
 esb:
  image: esb
  build:
   context: ./src/ESB
  ports:
   - "8082:8082"
  depends_on:
   - repartidor
   - restaurante
  environment:
   - PORT=90
   - IP=restaurante
   - IPR=repartidor
  networks:
   - docker_xxx
 restaurante:
  image: restaruante    
  build:
   context: ./src/Restaurante
  ports:
   - "8081:8081"
  depends_on:
   - repartidor
  environment:
   - PORT=90
   - IP=esb
  networks:
   - docker_xxx
 cliente:
  image: cliente
  build:
   context: ./cliente
  depends_on:
   - esb
  environment:
   - PORT=90
   - IP=esb
  networks:
   - docker_xxx
networks:
    docker_xxx:
      driver: bridge
