version: '3.3'

services:
 repartidor:
  image: repartido
  ports:
   - "8080:8080"
  networks:
   - docker_xxx
 esb:
  image: esb
  ports:
   - "8082:8082"
  depends_on:
   - repartidor
   - restaurante
  environment:
   - PORT=80
   - IP=restaurante
   - IPR=repartidor
  networks:
   - docker_xxx
 restaurante:
  image: restaruante    
  ports:
   - "8081:8081"
  depends_on:
   - repartidor
  environment:
   - PORT=80
   - IP=esb
  networks:
   - docker_xxx
 cliente:
  image: cliente
  depends_on:
   - esb
  environment:
   - PORT=80
   - IP=esb
  networks:
   - docker_xxx
networks:
    docker_xxx:
      driver: bridge
